/*
Reads the locks csv file and outputs the same file with the accounts
generated by a hd wallet and divides all quantities by 10000
 */

import dotenv from 'dotenv';
dotenv.config();

import fs from "fs";
import {parse} from "csv-parse";
import HDWallet from "ethereum-hdwallet";
import {ethers} from "ethers";

const mnemonic = process.env.TESTNET_WALLET_MNEMONIC;
if (!mnemonic){
    console.error(`You must set TESTNET_WALLET_MNEMONIC to use this function`);
    process.exit(1);
}
const hdwallet = HDWallet.fromMnemonic(mnemonic);
const wallet = hdwallet.derive(`m/44'/60'/0'/0`);
let wallet_index = 0;
const count_test = process.argv[2] || 500;

(async () => {
    const infile = './locks-collated.csv';
    const outfile = './locks-collated-test.csv';

    console.log(`Creating test lock file with controlled accounts and lower quantities, ${count_test} rows`);
    const parser = fs
        .createReadStream(infile)
        .pipe(parse({}));
    let csv_data = [];
    let totals = {
        1: 0n,
        2: 0n,
        3: 0n,
    };
    for await (const record of parser) {
        // For testnet, swap account and divide quantity by 10000
        record[0] = `0x${wallet.derive(wallet_index++).getAddress().toString('hex')}`;
        const qty_bn = BigInt(record[1]);
        record[1] =  (qty_bn / 10000n).toString();

        const [account, quantity, token_type] = record;

        totals[token_type] = totals[token_type] + BigInt(quantity);

        csv_data.push(`${account},${quantity},${token_type}`);
        if (count_test > 0 && csv_data.length >= count_test && process.env.BLAST_ENV === 'testnet'){
            break;
        }
    }
    fs.writeFile(outfile, csv_data.join(`\n`), () => {
        console.log(`${outfile} written`);
        process.exit(0);
    });

    console.log('Totals', totals);
    console.log(`ETH : ${totals[1].toString()} ${ethers.formatEther(totals[1])}`);
    console.log(`USDB : ${totals[2].toString()} ${ethers.formatEther(totals[2])}`);
    console.log(`WETH : ${totals[3].toString()} ${ethers.formatEther(totals[3])}`);
})();
